### ISSUE TITLE
VanillaOS APX GUI app doesn't launch 

### ISSUE THREAD

**Issue by Blumoop** [Kanola-Images/Kanola#1]
### Issue Description

Just recently switched over to the Kanola Plasma image a few days ago on a test laptop, and updated to Vanilla OS Orchid today. So far I have found that the APX app that's included with Vanilla OS, will not launch, or doesn't appear to. The process doesn't seem to appear in System Monitor or GNOME System Monitor either. I have tried restarting and it still will not launch. 

### Steps to Reproduce

- Install Vanilla OS without any configurations
- Switch over to Kanola KDE image
- Try to launch the APX GUI app, it will do the loading on the icons only task manager and then nothing happens

### On what version of Kanola does this happen?

Unreleased

### Additional Information

This laptop (Lenovo V15 G4 IRU) is on Vanilla OS 2.0 and Wayland with intel graphics, if that helps. I have no idea if this also happens before the Orchid update. Originally this laptop was running the #132 beta build, before I switched it to Kanola.

I would like to know if anyone else had this issue when testing Kanola or is it just me?

**Comment by chymian** [comment]
@Blumoop you need `python3-requests` installed. it's a missing dependency.
```
abroot pkg add python3-requests
abroot upgrade
reboot
```

**Comment by Blumoop** [comment]
At first that didn't seem to solve the issue, however I did this instead
`abroot pkg add python3-requests`
`abroot pkg apply python3-requests`

Reboot the system and now the APX app launches like it does on Vanilla OS. Thanks for the help!
