### ISSUE TITLE
Unable to use kde-coonect

### ISSUE THREAD

**Issue by ghost** [Kanola-Images/Kanola#10]
### Issue Description

kdeconnect is blocked by firewall by default

### Steps to Reproduce

Connect phone and system to same wifi
open kdeconnect , no new devices shown in either the desktop kdeconnect app or the android kdeconnect app 

### On what version of Kanola does this happen?

Unreleased

### Additional Information

adding a firewall rule for kdeconnect fixes it , but it should be allowed be default if kdeconnect comes preinstalled

**Comment by Maxwelldoug** [comment]
Frankly, I have no idea what's going on here. I didn't think kde connect was even a default app. I'll look into it along with the rest when I have time.

**Comment by ghost** [comment]
It works after adding firewall rule from Plasma Settings >Firewall
