### ISSUE TITLE
Please add kde-spectacle for taking screenshots by default 

### ISSUE THREAD

**Issue by ghost** [Kanola-Images/Kanola#11]
### Feature Description

Adding Spectacle would allow user to share screenshots easily for bug reports 

### Rationale

Every kde-plasma distro has it by default , using abroot to manually tinker for a basic utility tool is not ideal 

### Additional Information

package name is `kde-spectacle`

**Comment by Maxwelldoug** [comment]
Spectacle will be installed during the first run installer once I figure out what's causing it to crash repeatedly, same as the gnome image's snapshot app. For now, you should be able to install it via the software store as a workaround.
