### ISSUE TITLE
System Settings/Date & Time missing

### ISSUE THREAD

**Issue by domesinrome** [Kanola-Images/Kanola#2]
### Issue Description

My clock is set to Eastern Daylight Time. I live in the central time zone. When installing a new operating system, since the 1980's, I've always chosen Chicago because it was in every OS database since the Amiga. That's the city I chose at time of installation. System Settings/Date & Time is missing.

### Steps to Reproduce

Right click on the clock on the taskbar, choose "Adjust Date & Time"

### On what version of Kanola does this happen?

Unreleased

### Additional Information

![ksnip_20240728-230135](https://github.com/user-attachments/assets/c808b376-c63b-43b4-a9c0-54c2a7be374e)
![ksnip_20240728-230343](https://github.com/user-attachments/assets/d61fe446-e119-4d2d-89bf-7d7f265beaae)

**Comment by Maxwelldoug** [comment]
The Date and Time settings are under "Regional Settings" in plasma 5, can you please check there?

Edit: Also, I sincerely apologize for the delayed reply, I've been in summer courses and just finished exams yesterday so I've been swamped and for some reason, I am not receiving notifications about new issues.

**Comment by domesinrome** [comment]
I remember doing that at the time. All of the regional entries had exactly the same time zone. It was pretty weird. It turned out that I'm too new to Linux for smaller distros with minimal documentation so I've retreated back to being a Debian user. Unfortunately I wasn't able to make Vanilla work for me. My requests for support on Discord (unrelated to Kanola) were going unaddressed and I just don't have the knowledge to figure out on my own why an update breaks my monitor. I'll check back in six months or a year and see how things are coming along. Best of luck to you!
