### ISSUE TITLE
No way to change wallpaper

### ISSUE THREAD

**Issue by zymsbgt** [Kanola-Images/Kanola#4]
### Issue Description

The default wallpaper screen is black and there is no way to set a wallpaper

### Steps to Reproduce

- Install VanillaOS with nplasma:main image
- Right click anywhere on the desktop

### On what version of Kanola does this happen?

Unreleased

**Comment by Maxwelldoug** [comment]
I have not encountered this, can you check if it works on a non nvidia system with the plasma:main image? It does on my clients, but there may be some difference in your setup and I'd like to clear variables.

**Comment by Maxwelldoug** [comment]
I have confirmed this is not a reproducible issue in VM or real hardware on the current main and dev builds of Kanola, so I will close this issue. If you can provide a path to reproduce it, you can add it here and mention me, or create a new issue for elevated visibility.
